apiVersion: v1
kind: ConfigMap
metadata:
 name: jairh3110-config
 labels:
   app: postgres
data:
 PROD_SECRET_KEY: i-love-adsoftsito-dev
 PROD_DATABASE: 'jbzieqjg'
 PROD_USER: 'jbzieqjg'
 PROD_PASSWORD: 'HSVKMnjgfYyBL7pLjAlCfsmm-uyZBRXy'
 PROD_PORT: "5432"
 PROD_HOST: 'rosie.db.elephantsql.com'
