# Generated by Django 3.1.3 on 2023-06-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(default='')),
                ('modelo', models.TextField(default='')),
                ('prompt', models.TextField(default='')),
                ('resultado', models.URLField(default='')),
                ('fecha', models.TextField(default='')),
            ],
        ),
    ]
