# Generated by Django 3.1.3 on 2023-02-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faccion', models.TextField(default='')),
                ('raza', models.TextField(default='')),
                ('rango', models.TextField(default='')),
                ('caracteristicas', models.TextField(default='')),
                ('peligrosidad', models.TextField(default='')),
                ('representantes', models.TextField(default='')),
                ('origen', models.TextField(default='')),
                ('especialidad', models.TextField(default='')),
                ('antiguedad', models.TextField(default='')),
            ],
        ),
    ]
